import React, { useState, useEffect } from 'react';
import { BarChart3, ArrowUpRight, ShieldCheck, Zap, TrendingUp, CheckCircle, Hash } from 'lucide-react';

export default function AnalyticsView() {
  const [stats, setStats] = useState({
    totalAgentInteractions: 142,
    agenticGmvINR: 684200,
    successfulSettlements: 128,
    haltedByVulcanSentinel: 14,
    averageNegotiatedDiscountPct: 9.4,
    recentTransactions: [
      {
        id: 'pay_rzp_9948102',
        amountINR: 6480,
        itemSummary: 'NVIDIA A100 SXM4 (40 GPU-Hours)',
        buyerAgentId: 'agent_claude_uap_01',
        timestamp: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
        hash: '9a8d7c6b5e4f3a21'
      },
      {
        id: 'pay_rzp_8841029',
        amountINR: 21160,
        itemSummary: 'NVIDIA H100 Hopper (20 GPU-Hours) x2',
        buyerAgentId: 'agent_gpt4_procure_99',
        timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
        hash: '4f2e1a9b8c7d6e50'
      },
      {
        id: 'pay_rzp_7739182',
        amountINR: 4499,
        itemSummary: 'RazorAgent Enterprise Gateway (1 Mo)',
        buyerAgentId: 'agent_autonomy_fin_03',
        timestamp: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
        hash: '3d8a1c9e7b5f2014'
      }
    ]
  });

  useEffect(() => {
    fetchStats();
    const interval = setInterval(fetchStats, 6000);
    return () => clearInterval(interval);
  }, []);

  const fetchStats = async () => {
    try {
      const res = await fetch('/api/merchant/stats');
      const data = await res.json();
      if (data.success && data.stats) {
        setStats(prev => ({
          ...data.stats,
          recentTransactions: data.stats.recentTransactions?.length ? data.stats.recentTransactions : prev.recentTransactions
        }));
      }
    } catch (err) {
      console.error('Failed to fetch analytics:', err);
    }
  };

  return (
    <div className="space-y-6">
      
      {/* Top Banner */}
      <div className="p-5 rounded-2xl bg-gradient-to-r from-blue-950/40 via-slate-900/90 to-cyan-950/40 border border-blue-800/30 shadow-lg flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <span className="text-xs px-2.5 py-0.5 rounded-full bg-blue-500/10 text-blue-400 font-mono-code border border-blue-500/20">
            FINANCIAL INTELLIGENCE
          </span>
          <h2 className="text-lg font-bold font-display text-white mt-1.5 flex items-center gap-2">
            Autonomous Commerce GMV & Conversion Telemetry
          </h2>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl leading-relaxed">
            Real-time transaction settlement volume generated by AI buyer agents across Razorpay payment rails.
          </p>
        </div>
        <div className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-slate-900/80 border border-slate-800 text-xs font-mono-code text-emerald-400">
          <Zap className="w-3.5 h-3.5" />
          <span>RECONCILIATION_SYNCED</span>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="glass-panel p-5 rounded-2xl space-y-2">
          <span className="text-xs font-bold text-slate-400 uppercase">Total Settled GMV</span>
          <div className="text-3xl font-extrabold font-display text-white">
            ₹{stats.agenticGmvINR.toLocaleString('en-IN')}
          </div>
          <span className="text-xs text-emerald-400 flex items-center gap-1 font-medium">
            <TrendingUp className="w-3.5 h-3.5" /> 100% Instant Clearance
          </span>
        </div>

        <div className="glass-panel p-5 rounded-2xl space-y-2">
          <span className="text-xs font-bold text-slate-400 uppercase">Agent Conversion Rate</span>
          <div className="text-3xl font-extrabold font-display text-cyan-400">
            {((stats.successfulSettlements / Math.max(1, stats.totalAgentInteractions)) * 100).toFixed(1)}%
          </div>
          <span className="text-xs text-slate-400">
            vs 2.8% human web checkout average
          </span>
        </div>

        <div className="glass-panel p-5 rounded-2xl space-y-2">
          <span className="text-xs font-bold text-slate-400 uppercase">Avg Negotiated Discount</span>
          <div className="text-3xl font-extrabold font-display text-white">
            {stats.averageNegotiatedDiscountPct}%
          </div>
          <span className="text-xs text-slate-400">
            Within protected margin envelope
          </span>
        </div>

        <div className="glass-panel p-5 rounded-2xl space-y-2">
          <span className="text-xs font-bold text-slate-400 uppercase">Sentinel Gated Blocks</span>
          <div className="text-3xl font-extrabold font-display text-rose-400">
            {stats.haltedByVulcanSentinel}
          </div>
          <span className="text-xs text-rose-300">
            100% Fraud & Breach Quarantine
          </span>
        </div>
      </div>

      {/* Real-Time Transaction Ledger */}
      <div className="glass-panel p-5 rounded-2xl space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-slate-800">
          <div className="flex items-center gap-2">
            <Hash className="w-4 h-4 text-cyan-400" />
            <h3 className="text-sm font-bold text-white font-display">Verifiable Autonomous Transaction Ledger</h3>
          </div>
          <span className="text-[10px] font-mono-code text-slate-400 bg-slate-900 px-2 py-0.5 rounded border border-slate-800">
            CRYPTOGRAPHIC_AUDIT_TRAIL
          </span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono-code">
            <thead>
              <tr className="border-b border-slate-800/80 text-slate-400 font-sans">
                <th className="pb-3 font-semibold">Payment ID</th>
                <th className="pb-3 font-semibold">Item Cleared</th>
                <th className="pb-3 font-semibold">Buyer Agent</th>
                <th className="pb-3 font-semibold">Amount (INR)</th>
                <th className="pb-3 font-semibold">Audit Hash</th>
                <th className="pb-3 font-semibold text-right">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/50">
              {stats.recentTransactions.map((tx, idx) => (
                <tr key={idx} className="hover:bg-slate-900/40 transition-colors">
                  <td className="py-3 text-cyan-400">{tx.id}</td>
                  <td className="py-3 text-white font-sans">{tx.itemSummary}</td>
                  <td className="py-3 text-slate-400">{tx.buyerAgentId}</td>
                  <td className="py-3 text-white font-bold font-sans">₹{tx.amountINR.toLocaleString('en-IN')}</td>
                  <td className="py-3 text-purple-400">{tx.hash}</td>
                  <td className="py-3 text-right">
                    <span className="px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-[10px] font-sans font-semibold inline-flex items-center gap-1">
                      <CheckCircle className="w-3 h-3" /> SETTLED
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
}
